### ISSUE TITLE
Inconsistency with keyPrefix

### ISSUE THREAD

**Issue by pedrokost** [ember-cli-deploy/ember-cli-deploy-redis#59] opened 2016-05-21 16:00 UTC
My Redis config contains the following:

```
redis: {
    allowOverwrite: true,
    keyPrefix: 'zatresi',
    maxRecentUploads: 100
},
```

When I run `ember deploy prod` I get the following output:

```
- Deployed but did not activate revision eb65b18c84b6b6b373fa5315e6661a9b. To activate, run: ember deploy:activate prod --revision=eb65b18c84b6b6b373fa5315e6661a9b
```

In Redis, the key `zatresi:eb65b18c84b6b6b373fa5315e6661a9b` indeed contains the HTML content of the `index.html` file.

Next, I run:

```
ember deploy:activate prod --revision=eb65b18c84b6b6b373fa5315e6661a9b
```

**This sets the value of they key `zatresi:current` to `eb65b18c84b6b6b373fa5315e6661a9b` instead of `zatresi:eb65b18c84b6b6b373fa5315e6661a9b`.** I believe this is a regression from a much earlier version of the addon. At some point, the behavior changed.

The documentation says:

> The unique revision number for the version of the file being uploaded to Redis. The Redis key will be a combination of the keyPrefix and the revisionKey. By default this option will use either the revisionKey passed in from the command line or the revisionData.revisionKey property from the deployment context.
> 
> Default: `context.commandLineArgs.revisionKey || context.revisionData.revisionKey`

I believe the default should instead be: `keyPrefix + context.commandLineArgs.revisionKey || context.revisionData.revisionKey`

Also, from this documentation it is not clear how I can override the `revisionKey` parameter. Can I pass a function which accepts the `keyPrefix` and/or `context` to it?

**Comment by achambers** [comment] 2016-05-21 16:40
Hi @pedrokost.

The functionality that you are describing is quite intentional.

It is by design that `<keyPrefix>:current` points to the *Revision Key* and not the *Redis Key*.

Redis will combine the `keyPrefix` property and the `revisionKey` property to determine the *Redis Key*. Therefore it doesn't make sense for the `revisionKey` property to either accept the `keyPrefix` or return a value containing it. The `revisionKey` is supposed to be the unique value that identifies the revision.

Hope this cleared things up a bit. I'm going to close this issue as there is nothing to be changed here.

If you have any other questions or need something clarified more, by all means ask them here, or reopen this if you need to.

**Closed by achambers** 2016-05-21 16:40 UTC

**Comment by pedrokost** [comment] 2016-05-21 19:42
@achambers OK

Why wouldn't the `revisionKey` and the _Redis Key_ be the same? Wouldn't this remove one possible source of confusion?

**Comment by achambers** [comment] 2016-05-21 19:44
@pedrokost What confusion is that?

**Comment by pedrokost** [comment] 2016-05-21 20:01
@achambers Nevermind. I only stumbled upon this because I was upgrading from `ember-deploy-redis#0.0.7` to `ember-cli-deploy-redis`.

In the former `prefixKey:current` points to the actual HTML, but in the latter it points to a reference key. Instead the content is in `prefixKey:current-content` by default. 

I can work around this without changing the server side code by renaming `activationSuffix` to `current-pointer` and `activeContentSuffix` to `current`.
